In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Tuition_Assistance_20240525.csv")
df

,Department,Major,Degree,School,Course Title,Course Description,Cost
0,Police,Business/Admin./Mgmt.,AA,Montgomery College Rockville Campus,INTRODUCTION TO BUSINESS,An introductory course designed to survey the ...,392.0
1,Police,Business/Admin./Mgmt.,AA,Montgomery College Rockville Campus,MA 160,A general calculus course primarily for busine...,392.0
2,Police,Business/Admin./Mgmt.,AA,Montgomery College Rockville Campus,INTRO TO AMERICAN MUSIC,A survey of American popular music from the tu...,392.0
3,Health & Human Services,Business/Admin./Mgmt.,Masters (MA/MS/MPH/etc.),BOWIE STATE UNIVERSITY,PUBLIC POLICY ANALYSIS,Focus is on the analysis of costs and benefits...,1062.0
4,Health & Human Services,Other/Misc.,Masters (MA/MS/MPH/etc.),Mount St Mary's University,MHA 500 CONTEMPORARY ISSUES IN HEALTH CARE,"The historical, current, and future organizati...",1569.0
...,...,...,...,...,...,...,...
4363,Police,Political Science,Bachelors (BA/BS),MONTGOMERY COUNTY COMMUNITY COLLEGE,POL 101 AMERICAN GOVERMENT,"Structure, powers, and processes of the Americ...",402.0
4364,Fire/Rescue Services,NaN,Non-Degree,FIRE DEPARTMENT TRAINING NETWORK,FIREGROUND SURVIVAL & RIT,Fire Combat,1200.0
4365,Liquor Control,Information Technology,AA,MONTGOMERY COUNTY COMMUNITY COLLEGE,UNIX/LINUX SYSTEM ADMINISTRATION,These are Saturday classes.\n\nIntroduction to...,528.0
4366,Police,Other/Misc.,Other,Victory First,RDS HANDGUN INSTRUCTOR,RDS Handgun Instructor for LEO only,750.0
4367,Transportation,Civil and Environmental Engineering,Bachelors (BA/BS),Montgomery College Rockville Campus,ART 101- INTRODUCTION TO DRAWING,An introduction to drawing and creative visual...,336.0

In [40]:
dados_sem_nan = df.dropna()
dados_sem_nan = df.dropna(axis=0)

In [38]:
school_exp_idx = df['Cost'].idxmax()
school_exp = df.iloc[school_exp_idx]

school_name = school_exp['School']
school_cost = school_exp['Cost']
print(f"Escola com maior custo: {school_name} - R$ {school_cost:.2f}")

Escola com maior custo: Chicago School of Professional Psychology - R$ 2300.00

In [43]:
#showing the expensives schools (without NaNs values)
no_nan = df.dropna()
no_nan = df.dropna(axis=0)
df_ordenado = no_nan.sort_values(by='Cost', ascending=False)

top_10 = df_ordenado.head(10)
top_10

,Department,Major,Degree,School,Course Title,Course Description,Cost
4280,Health & Human Services,Psychology,Certificate,Chicago School of Professional Psychology,ONLINE LEARNING COMMUNITIES AND PEDAGOGIES,This course provides a foundation of the best ...,2300.0
4254,Sheriff,Psychology,Masters (MA/MS/MPH/etc.),HOOD COLLEGE,COUN 507: TRAUMA & CRISIS INTERVENTIONS,This course provides the counseling student wi...,2295.0
4003,Health & Human Services,Business/Admin./Mgmt.,Masters (MA/MS/MPH/etc.),University of Maryland Global Campus,MBA FUNDAMENTALS,PRO 600 Pre-req by plan Master of Business Adm...,2200.0
4129,Health & Human Services,Special Education,Masters (MA/MS/MPH/etc.),GEORGE MASON UNIVERSITY,AUTISM AND SENSORY PROCESSING DISORDERS,EDSE 636 Supporting Communication and Literacy...,2200.0
3652,Police,Business/Admin./Mgmt.,Masters (MA/MS/MPH/etc.),University of Maryland Global Campus,MBA 610 LEADING ORGANIZATIONS AND PEOPLE,Assess and develop your leadership skills by c...,2200.0
4195,Health & Human Services,Psychology,Ph.D. (DCS),WALDEN UNIVERSITY,COUN 8125: TEACHING IN COUNSELOR EDUCATION,"In this course, students prepare to become com...",2200.0
4023,Transportation,Health & Human Services,Ph.D. (DCS),WALDEN UNIVERSITY,DISSERTATION 9001,"Through this course, doctoral students have th...",2200.0
4028,Health & Human Services,Nursing,Masters (MA/MS/MPH/etc.),WALDEN UNIVERSITY,PSYCHOPATHOLOGY,Psychiatric Mental Health Nurse Practitioner,2200.0
3612,Health & Human Services,Accounting (Business),Masters (MA/MS/MPH/etc.),University of Maryland - College Park,BUSO 602 FINANCIAL ACCOUNTING,"Overview of financial accounting, periodic fin...",2200.0
4163,Health & Human Services,Business/Admin./Mgmt.,Masters (MA/MS/MPH/etc.),University of Maryland - University College,"PRO 600 COMMUNICATING, PROBLEM SOLVING, AND LE...",Make yourself more valuable to an employer by ...,2200.0

In [45]:
#showing de cheaper schools (without NaNs values)
filtro_df = no_nan[no_nan['Cost'] > 0]
df_ordenado = filtro_df.sort_values(by='Cost', ascending=True)


top_10_cheap = df_ordenado.head(10)
top_10_cheap

,Department,Major,Degree,School,Course Title,Course Description,Cost
2579,Police,Computer Science,Bachelors (BA/BS),"UNIVERSITY OF MARYLAND, UNIVERSITY COLLEGE",MATH 115 - PRE-CALCULUS,Pre-Calculus\n\nMATH 115 | 3 Credits\n\n(Not o...,1.0
413,Police,Not Listed,Ph.D. (DDE),Wilmington University,EDD7107: DISCIPLINE INQUIRY II,The main focus of the second of this two-cours...,1.0
427,Police,Not Listed,Ph.D. (DDE),Wilmington University,EDD7204: ART OF LEADERSHIP,The purpose of this course is to examine past ...,1.0
428,Police,Not Listed,Ph.D. (DDE),Wilmington University,EDD 7202: DATA DRIVEN DECISION MAKING,This course examines how data can be used in d...,1.0
2546,Fire/Rescue Services,Public Safety,Bachelors (BA/BS),University of Maryland - University College,WRTG 394 ADVANCED BUSINESS WRITING,"A comprehensive, project-based study of applie...",6.0
578,Finance,Nursing,AA,NATIONAL ASSOCIATION OF HOUSING AND REDEVELOPM...,GENERAL PSYCHOLOGY,Introduction to the fields and research method...,7.4
576,Finance,Nursing,AA,NATIONAL ASSOCIATION OF HOUSING AND REDEVELOPM...,PRINCIPLES OF BIOLOGY 107,First in a two semetre sequence natural science.,7.4
134,Fire/Rescue Services,Other/Misc.,Bachelors (BA/BS),COLUMBIA SOUTHERN UNIVERSITY,STUDENT LEARNING SUCCESS,Introduces students to the skills that will pr...,30.0
135,Fire/Rescue Services,Other/Misc.,Bachelors (BA/BS),COLUMBIA SOUTHERN UNIVERSITY,ENGLISH,Introduction to the basic concepts and require...,30.0
1853,Finance,Accounting (Business),Certificate,"Professional Education Services, LP",ETHICS AND STANDARDS OF CONDUCT FOR VIRGINIA C...,This course is designed to meet the specific e...,34.5

In [46]:
mean = no_nan['Cost'].mean()
mean

785.8304981152396

In [4]:
#most expensives schools (by mean)
mean_costs = df.groupby('School')['Cost'].mean()
sorted_mean_costs = mean_costs.sort_values(ascending=False)
sorted_mean_costs

School
UNIVERSITY OF MARYLAND AT BALTIMORE                            2200.0
YALE UNIVERSITY                                                2200.0
Personality Insights                                           2194.0
University of Vermont                                          2130.0
Johnson & Wales University                                     2130.0
                                                                ...
International Association of Financial Crimes Investigators     100.0
HOMEFRONT PROTECTIVE GROUP                                       95.0
Institute for Natural Resources (INR)                            81.0
Pace Institute                                                   60.0
Professional Education Services, LP                              44.5
Name: Cost, Length: 382, dtype: float64

In [9]:
#mean cost by department
cost_by_department = df.groupby('Department')['Cost'].mean().reset_index()
cost_by_department1 = cost_by_department.sort_values(by='Cost', ascending=False)
cost_by_department1

                                    Department         Cost
23                   Office of Labor Relations  1550.000000
7                               County Council  1525.000000
19                       Legislative Oversight  1320.000000
2                 Community Engagement Cluster  1290.225000
4                          Consumer Protection   990.000000
9           Emergency Mgmt & Homeland Security   940.000000
30                                     Sheriff   919.650000
1                           Board of Elections   895.000000
18                         Investment Trustees   894.504167
5                  Correction & Rehabilitation   884.436244
25                         Permitting Services   876.093750
16                             Human Resources   863.698113
32                         Technology Services   839.700000
14                     Health & Human Services   832.628016
20                                   Libraries   816.252500
26                                      Police   813.370835
21                              Liquor Control   797.943708
27                                 Procurement   795.000000
12                        Fire/Rescue Services   755.565073
33                              Transportation   703.836778
13                            General Services   694.799099
11                                     Finance   668.302321
29                                  Recreation   660.412000
22                         Management & Budget   659.117647
10                    Environmental Protection   644.671233
3              Community Use Public Facilities   610.845238
28                          Public Information   603.850000
15                 Housing & Community Affairs   597.574237
17                                Human Rights   565.000000
31                            State's Attorney   564.473778
0                              Animal services   509.142857
6                              County Attorney   395.224000
24  Office of Racial Equity and Social Justice   345.000000
8                             County Executive   336.000000

In [10]:
#total cost by school
cost_per_school = df.groupby('School')['Cost'].sum().reset_index()
cost_per_school = cost_per_school.sort_values(by='Cost', ascending=False)
cost_per_school

                                                School       Cost
355        University of Maryland - University College  534339.07
344         UNIVERSITY OF MARYLAND, UNIVERSITY COLLEGE  175946.80
304                                 STRAYER UNIVERSITY  100377.50
356               University of Maryland Global Campus   93786.80
233                Montgomery College Rockville Campus   88487.58
..                                                 ...        ...
258  OFFICE OF EDUCATION AND TRAINING FOR ADDICTION...     160.00
56                                       CALIBRE PRESS     139.00
174  International Association of Financial Crimes ...     100.00
169              Institute for Natural Resources (INR)      81.00
271                                     Pace Institute      60.00

[382 rows x 2 columns]

In [13]:
#number of courses by school
courses_numbers_by_school = df.groupby('School')['Course Title'].count().reset_index()
courses_numbers_by_school = courses_numbers_by_school.rename(columns={'Course Title': 'Course Count'})
courses_numbers_by_school = courses_numbers_by_school.sort_values(by='Course Count', ascending=False)
courses_numbers_by_school

                                                School  Course Count
355        University of Maryland - University College           665
233                Montgomery College Rockville Campus           237
344         UNIVERSITY OF MARYLAND, UNIVERSITY COLLEGE           210
219                       MONTGOMERY COMMUNITY COLLEGE           195
115                        FREDERICK COMMUNITY COLLEGE           141
..                                                 ...           ...
151  Harvard Medical School, Massachusetts Mental H...             1
288                     RedVector Convergence Training             1
153                           HealthSciences Institute             1
286  RUTGERS UNIVERSITY - NEWARK - SCHOOL OF PUBLIC...             1
0                          A & W Health Care Educators             1

[382 rows x 2 columns]